- name: server
  hosts: all
  become: True
  gather_facts: no
  vars_files:
    - ansible_vars/main.yaml

  pre_tasks:
    - name: Wait for system to become reachable
      wait_for_connection:

  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: 
          - "{{ env }}"

    - name: Creating apt file for set elasticsearch version
      file:
        state: touch
        path: /etc/apt/sources.list.d/elastic-7.x.list

    - name: Add an Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Set elasticsearch version 7 to apt repository list
      lineinfile:
        path: /etc/apt/sources.list.d/elastic-7.x.list
        line: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"

    - name: apt upgrade 
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install APT packeges
      apt:
        name: 
          - default-jre
          - default-jdk
          - nginx
          - elasticsearch
          - kibana
          - logstash
          - awscli
        state: present
        update_cache: yes

    - name: Install certbot
      apt:
        name:
          - certbot
          - python3-certbot-dns-route53
        state: present
        update_cache: yes
      when: env != "vagrant"

    - name: Set default host for elasticsearch
      lineinfile:
        path: /etc/elasticsearch/elasticsearch.yml
        line: "network.host: localhost"

    - name: Copy config file for logstash
      copy:
        src: ./logstash.conf
        dest: /etc/logstash/conf.d/logstash.conf

    - name: Copy htpasswd file
      copy:
        src: ./nginx/htpasswd.users
        dest: /etc/nginx/htpasswd.users
      when: env != "vagrant"

    - name: Copy docker config for vagrant machine
      copy:
        src: ./nginx/local.conf
        dest: /etc/nginx/conf.d/
      when: env == "vagrant"

    - name: Copy nginx config for deployment with domain
      copy:
        src: ./nginx/elk.feature-testing.link.conf
        dest: /etc/nginx/conf.d/
      when: env != "vagrant"

    - name: Ensure .aws directory under user home for awscli config
      file:
        path: "/home/{{ item.username }}/.aws"
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: 0755
      when: item.get('state', 'present') == 'present'
      with_items: "{{ awscli_users }}"

    - name: Copy awscli config to remote server
      template:
        src: awscli_config.j2
        dest: "/home/{{ item.username }}/.aws/config"
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: 0644
      when: item.get('state', 'present') == 'present'
      with_items: "{{ awscli_users }}"

    - name: Start certbot
      shell: certbot certonly --dns-route53 --noninteractive --text --expand --agree-tos --email {{ email }} -d {{ domain }}
      when: env != "vagrant"

    - name: Start services, if not started
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - elasticsearch
        - logstash
        - kibana
        - nginx